Ensure that "str" argument or lwres__print_sprintf() is not NULL
GCC 11 from Fedora 34 fails to build lib/lwres/print.c when
AddressSanitizer is enabled due to the "str" argument being possibly
NULL:

    print.c: In function ‘lwres__print_sprintf’:
    print.c:32:9: error: null destination pointer [-Werror=format-overflow=]
       32 |         vsprintf(str, format, ap);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~